In [1]:
dataName = 'crudeOilFeb'
dataFrequency='5m'

import os
import sys  
module_path = os.path.abspath('../../'+os.path.join('.'))

sys.path.append(module_path)

print("module_path >>> " + module_path + " <<< appended to sys path - Mandatory for the pythons files in src folder to be recognized")

module_path >>> /Users/493055/Desktop/dev/erai-v0.3/src <<< appended to sys path - Mandatory for the pythons files in src folder to be recognized

In [2]:
from dataPreparation import *

from dataPreparation.platform import createPlatform, createFundamentalFeatures

baseDf = createPlatform(dataName,dataFrequency)

baseInputDf = createFundamentalFeatures(baseDf)  # data with open close high low

into method doBasicOperation
 retrieving values configured in >>> /Users/493055/Desktop/dev/erai-v0.3/src/config/config.json
before return statement of method doBasicOperation
added INPUT FEATURES >>> 4 count >>> open-high-low-close

In [3]:
baseInputDf.tail()

      open  high   low  close
6892  3629  3634  3629   3634
6893  3634  3637  3632   3636
6894  3636  3637  3621   3624
6895  3623  3626  3620   3623
6896  3622  3625  3620   3621

In [4]:
dataDf = baseInputDf

In [7]:
from dataPreparation.dataAnalyticFeatures import getLinearWeightedMovingAverageFeatures
from dataPreparation.platform import saveFeatureToDisk

lwmaDf=getLinearWeightedMovingAverageFeatures(baseInputDf)
saveFeatureToDisk(dataName,dataFrequency,lwmaDf,'005_linear_weighted_moving_average')

 checking if folder existis >>>/Users/493055/Desktop/dev/erai-v0.3/data/crudeOilFeb/processed/5m/features

'/Users/493055/Desktop/dev/erai-v0.3/data/crudeOilFeb/processed/5m/features/004_linear_weighted_moving_average.csv'

In [8]:
lwmaDf.head(15)

,lwma_10,lwma_12,lwma_13,lwma_20,lwma_26,lwma_30,lwma_40,lwma_50,lwma_60,lwma_70,...,lwma_110,lwma_120,lwma_130,lwma_140,lwma_150,lwma_160,lwma_170,lwma_180,lwma_190,lwma_200
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3790.054545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3789.345455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3789.036364,3789.166667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3788.163636,3788.487179,3788.571429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3787.563636,3788.000000,3788.131868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3787.436364,3787.833333,3788.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN